# GitHub Sponsors configuration for AvilaOps

github: [avilaops]
# patreon: avilaops
# open_collective: avilaops
# ko_fi: avilaops
# custom: ["https://avilaops.com/sponsor", "https://paypal.me/avilaops"]
